"""modelo pubs

Revision ID: 08914e46310c
Revises: c7d86551d2aa
Create Date: 2023-02-27 23:29:45.890968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08914e46310c'
down_revision = 'c7d86551d2aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuerpo', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pubs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pubs_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pubs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pubs_timestamp'))

    op.drop_table('pubs')
    # ### end Alembic commands ###
