"""modelo pubs

Revision ID: 7f56a09da4f0
Revises: af6372069796
Create Date: 2023-03-01 21:31:16.743896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f56a09da4f0'
down_revision = 'af6372069796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index('ix_usuario_ultima_sesion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index('ix_usuario_ultima_sesion', ['ultima_sesion'], unique=False)

    # ### end Alembic commands ###
